version: "3.9"


secrets:
  user_name:
    file: ./user_name.txt
  pass:
    file: ./pass.txt

services:
  sidecar:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HOST_IP: ${DOCKER_GATEWAY_HOST:-host.docker.internal}
    environment:
      HOST_IP: ${DOCKER_GATEWAY_HOST:-host.docker.internal}
    secrets:
      - user_name
      - pass