version: "3.9"

services:
  sidecar:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HOST_IP: ${DOCKER_GATEWAY_HOST:-host.docker.internal}
    environment:
      HOST_IP: ${DOCKER_GATEWAY_HOST:-host.docker.internal}