version: "3.9"

services:
  sidecar:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER: archlinuxkvm
        SSHPASS: 1234
        HOST_IP: 172.17.0.1
    volumes:
    - log-data:/logs
volumes:
  log-data:
